### ISSUE TITLE
Can't se streamd chanels

### ISSUE THREAD

**Issue by Zaccov** [emilsvennesson/kodi-viaplay#18]
I cant access the streamd chanels

[01_KODI.log](https://github.com/emilsvennesson/kodi-viaplay/files/1733860/01_KODI.log)

**Comment by emilsvennesson** [comment]
Have you tried with the latest master? This was fixed a while ago (https://github.com/emilsvennesson/kodi-viaplay/commit/64bcf2439e1472efbae518e4f7163ddd720b1a1a).

**Comment by Zaccov** [comment]
It ont even list them in the menu

**Comment by emilsvennesson** [comment]
@Zaccov Try with the latest master now.

**Comment by emilsvennesson** [comment]
I'm closing this as it has been fixed as of version 2.1.0.

**Comment by Zaccov** [comment]
Hi is it possible that you need Viasat Tv To Go to get this to work. I have a regular Viaplay subscription and I still cant get it to work. Using the latest master
